name: Backup Last Published

on:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  BackupLastPublished:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Dependencies
        run:
          pip install -r requirements.txt
      - name: buckup last published
        env:
          HARPERDB_URL: ${{ secrets.HARPERDB_URL }}
          HARPERDB_USERNAME: ${{ secrets.HARPERDB_USERNAME }}
          HARPERDB_PASSWORD: ${{ secrets.HARPERDB_PASSWORD }}
          HARPERDB_SCHEMA: ${{ secrets.HARPERDB_SCHEMA }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: python3 src/backup_last_published.py
      - name: Setup git
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        run: |
          git config --local user.name GitHubActions
          git remote set-url origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
      - name: Git push, tag, upload assets
        run: |
          git checkout main
          git pull origin main
          git add -A
          DIFF=`git diff --cached --numstat | wc -l`
          if [ $DIFF -eq 0 ]; then
            exit 0
          fi
          git commit -am 'GitHub Actions commit' --allow-empty
          git push origin main