name: Run Subscriber

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "*/30 * * * *"

jobs:
  Subscriber:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install Dependencies
        run: |
          pip install poetry
          poetry config virtualenvs.create true
          poetry install
          source $(poetry env info --path)/bin/activate
      - name: Install termextract
        run: |
          source $(poetry env info --path)/bin/activate
          sh scripts/install_pytermextract.sh
      - name: Install fastText
        run: |
          source $(poetry env info --path)/bin/activate
          pip install pybind11
          sh scripts/install_fasttext.sh
      - name: Activate NLTK
        run: |
          source $(poetry env info --path)/bin/activate
          python scripts/activate_nltk.py
      - name: Check black format
        run: |
          source $(poetry env info --path)/bin/activate
          black src --check
      - name: Run RSS
        env:
          HARPERDB_URL: ${{ secrets.HARPERDB_URL }}
          HARPERDB_USERNAME: ${{ secrets.HARPERDB_USERNAME }}
          HARPERDB_PASSWORD: ${{ secrets.HARPERDB_PASSWORD }}
          HARPERDB_SCHEMA: ${{ secrets.HARPERDB_SCHEMA }}
          MONGODB_CONNECTION_STRING: ${{ secrets.MONGODB_CONNECTION_STRING }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          LOGGING_LEVEL: "INFO"
          SLEEP_TIME: "1"
        run: |
          source $(poetry env info --path)/bin/activate
          python src/main.py
