name: Run Subscriber

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "*/30 * * * *"

jobs:
  Subscriber:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Dependencies
        run:
          pip install -r requirements.txt
      - name: Install termextract
        run:
          sh scripts/install_pytermextract.sh
      - name: Install fastText
        run:
          sh scripts/install_fasttext.sh
      - name: Activate NLTK
        run:
          python scripts/activate_nltk.py
      - name: Check black format
        run:
          black src --check
      - name: Run RSS
        env:
          HARPERDB_URL: ${{ secrets.HARPERDB_URL }}
          HARPERDB_USERNAME: ${{ secrets.HARPERDB_USERNAME }}
          HARPERDB_PASSWORD: ${{ secrets.HARPERDB_PASSWORD }}
          HARPERDB_SCHEMA: ${{ secrets.HARPERDB_SCHEMA }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          LOGGING_LEVEL: "INFO"
          SLEEP_TIME: "1"
        run: python3 src/main.py
